### ISSUE TITLE
capture_track waiting for index pulse

### ISSUE THREAD

**Issue by Niteto** [adafruit/Adafruit_Floppy#1]
Capturing a track from index pulse to next index pulse will run into trouble when reading disks that are not index aligned, e.g. Amiga Disks. A sector might start before an the index and end after the index, flux transitions might be lost when the capture does not overlap.

**Comment by ladyada** [comment]
yah right now we're using 3.5" floppy drive only since we have those :)
what should we do in that case, just capture for n milliseconds? or 1.25 'rotations'?

**Comment by ladyada** [comment]
i think its fixed with https://github.com/adafruit/Adafruit_Floppy/commit/c84b536c647cd48e65ef6fdf1651c18814ee0373 - we read through the index pulse so we get an 'overlap' of readings
