### ISSUE TITLE
Adafruit_Floppy VS original Greaseweasle compatibility

### ISSUE THREAD

**Issue by rchyla** [adafruit/Adafruit_Floppy#27]
Hello!

I hope i didn't miss that information, but which version of original Greaseweasle FW is current 0.3 Adafruit_Floppy compatible with or is aiming to be compatible with?

I am currently struggling whether to pick Adafruit_Floppy as alternative to boot FW for my project, or use Pi Pico as passthrough in GW mode and let a BluePill to do the job.

I am more interested in writing disks than reading. Is Adafruit_floppy made mainly with reading disks in mind or both write/read capabilities are taken into account during developement?

**Comment by jepler** [comment]
Our greaseweazle-compatible firmware is believed to be compatible with the latest released version of GreaseWeazle, 1.21 at the time of writing.

If there's a specific reason to change the firmware version we report to the host computer, please let us know!
