### ISSUE TITLE
Drive emulation

### ISSUE THREAD

**Issue by jpnielsen** [adafruit/Adafruit_Floppy#3]
Thank you for making this.

Will you emulate a floppy drive too?

I have an old Korg N364 synthesizer with a broken drive. Would be nice to mount a Pico instead, perhaps with extra flash. or sdcard reader.

It's a Matsushita EME-216 KR according to the service manual - but some have 34 pin floppy drives.

<img width="218" alt="image" src="https://user-images.githubusercontent.com/27916597/147930267-30b3e75a-a84a-4555-846d-50805355d693.png">
<img width="368" alt="image" src="https://user-images.githubusercontent.com/27916597/147932242-e3f2f669-dc3d-4289-8b59-65f8e98774c0.png">

https://en.wikipedia.org/wiki/Floppy_disk_hardware_emulator
http://hxc2001.free.fr/floppy_drive_emulator/
https://github.com/keirf/FlashFloppy

**Comment by ladyada** [comment]
we don't have any plans for that *yet* but it ought to be possible to write the inverse of all the current functions! it would have to deal with the level shifting more seriously since there's a greater chance of having a 5V signal come in.

**Comment by jepler** [comment]
As of release 0.5.0 on the unreleased Adafruit Floppsy, read-only FM and MFM drive emulation is supported. This does not work with the Adafruit Floppy Featherwing because the direction of the data signals cannot be switched. It could work on homebrewed hardware.
